"""
Pact provider verification test.

Starts the provider app via app_runner.py (InMemory + state manager),
then runs the Pact verifier against the pact file generated by the consumer.

Run with: cd product-provider-service && PYTHONPATH=src .venv/bin/pytest tests/provider -v
         (or from repo root: make test-provider-verification)
"""

import os
import subprocess
import sys
import time
from pathlib import Path

import pytest
from pact.v3 import Verifier

PROVIDER_DIR = Path(__file__).resolve().parents[2]
PACTS_DIR = Path(__file__).resolve().parents[3] / "pacts"
PROVIDER_PORT = 3001
PROVIDER_URL = f"http://localhost:{PROVIDER_PORT}"
STATE_HANDLER_URL = f"{PROVIDER_URL}/_pact/provider_states"


@pytest.fixture(scope="module", autouse=True)
def provider_server():
    """
    Starts the Pact-mode provider (InMemory DB + state manager endpoint)
    as a subprocess, waits for it to become ready, then tears it down
    after all tests in this module complete.
    """
    env = {**os.environ, "PYTHONPATH": f"{PROVIDER_DIR / 'src'}:{PROVIDER_DIR / 'tests' / 'provider'}"}
    proc = subprocess.Popen(
        [sys.executable, str(PROVIDER_DIR / "tests" / "provider" / "app_runner.py")],
        env=env,
        cwd=str(PROVIDER_DIR),
    )

    _wait_for_server(PROVIDER_URL + "/products", timeout=10)

    yield proc

    proc.terminate()
    proc.wait()


def _wait_for_server(url: str, timeout: int) -> None:
    """Poll the provider until it responds or the timeout expires."""
    import urllib.request
    import urllib.error

    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            urllib.request.urlopen(url, timeout=1)
            return
        except (urllib.error.URLError, OSError):
            time.sleep(0.3)

    raise RuntimeError(f"Provider did not start within {timeout}s at {url}")


class TestProviderVerification:
    """
    Provider-side Pact verification.

    Verifies that the running provider honours every interaction
    defined in the consumer-generated pact file.
    """

    def test_provider_honours_contract_with_consumer(self) -> None:
        pact_file = PACTS_DIR / "product-consumer-service-product-provider-service.json"

        (
            Verifier("product-provider-service", "localhost")
            .add_transport(url=PROVIDER_URL)
            .state_handler(STATE_HANDLER_URL, teardown=False, body=True)
            .add_source(pact_file)
            .verify()
        )
